[package]
name = "nees"
version = "0.1.0"
edition = "2021"
license = "GPL3-0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield-struct = "0.8.0"
anyhow = { version = "1.0", default-features = false }
